"""add_checkin_monitoring_table

Revision ID: 0ff9a4ab8a6a
Revises: 37547802c77d
Create Date: 2025-10-15 17:14:58.375969

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0ff9a4ab8a6a"
down_revision: Union[str, Sequence[str], None] = "37547802c77d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "checkin_monitoring",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "monitored_at_utc",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("cpu_percent", sa.FLOAT(), autoincrement=False, nullable=True),
        sa.Column("memory_percent", sa.FLOAT(), autoincrement=False, nullable=True),
        sa.Column(
            "active_apps",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "visited_sites",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["attendance_sessions.id"],
            name=op.f("checkin_monitoring_session_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("checkin_monitoring_pkey")),
    )
    op.create_index(
        op.f("ix_checkin_monitoring_session_id"), "checkin_monitoring", ["session_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_checkin_monitoring_session_id"), table_name="checkin_monitoring")
    op.drop_table("checkin_monitoring")
    # ### end Alembic commands ###
