"""Add payroll tables and update employee model

Revision ID: 641108578efe
Revises: f1234567890
Create Date: 2025-11-17 15:25:54.388338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '641108578efe'
down_revision: Union[str, Sequence[str], None] = 'f1234567890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_worklogs_employee_id'), table_name='worklogs')
    op.drop_index(op.f('ix_worklogs_work_date'), table_name='worklogs')
    op.drop_table('worklogs')
    op.drop_index(op.f('ix_admins_admin_id'), table_name='admins')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_table('admins')
    op.add_column('employee_salary', sa.Column('pf_scheme', sa.Boolean(), nullable=False))
    op.add_column('employee_salary', sa.Column('esi_scheme', sa.Boolean(), nullable=False))
    op.add_column('employee_salary', sa.Column('gratuity_scheme', sa.Boolean(), nullable=False))
    op.add_column('employees', sa.Column('bank_name', sa.String(length=50), nullable=True))
    op.add_column('employees', sa.Column('ifsc_code', sa.String(length=11), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'ifsc_code')
    op.drop_column('employees', 'bank_name')
    op.drop_column('employee_salary', 'gratuity_scheme')
    op.drop_column('employee_salary', 'esi_scheme')
    op.drop_column('employee_salary', 'pf_scheme')
    op.create_table('admins',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_super_admin', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('admins_pkey'))
    )
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_index(op.f('ix_admins_admin_id'), 'admins', ['admin_id'], unique=True)
    op.create_table('worklogs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('work_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('task', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('duration_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('work_type', postgresql.ENUM('FEATURE', 'BUG_FIX', 'MEETING', 'TRAINING', 'SUPPORT', 'OTHER', name='worktype'), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('TODO', 'IN_PROGRESS', 'DONE', name='worklogstatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name=op.f('worklogs_employee_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('worklogs_pkey'))
    )
    op.create_index(op.f('ix_worklogs_work_date'), 'worklogs', ['work_date'], unique=False)
    op.create_index(op.f('ix_worklogs_employee_id'), 'worklogs', ['employee_id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('added_by', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('expenses_pkey'))
    )
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    # ### end Alembic commands ###
