"""change employee_salaries foreign key to employee_id

Revision ID: 6906856c4dde
Revises: 0525888c2c6c
Create Date: 2026-03-18 15:17:02.865751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6906856c4dde'
down_revision: Union[str, Sequence[str], None] = '0525888c2c6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monthly_summary_emp_month'), table_name='monthly_employee_summaries')
    op.drop_table('monthly_employee_summaries')
    op.drop_index(op.f('ix_checkin_monitoring_session_id'), table_name='checkin_monitoring')
    op.drop_table('checkin_monitoring')
    op.drop_index(op.f('ix_payroll_policies_id'), table_name='payroll_policies')
    op.drop_table('payroll_policies')
    op.drop_index(op.f('ix_evidence_session_type'), table_name='attendance_evidences')
    op.drop_index(op.f('ix_evidence_verified'), table_name='attendance_evidences')
    op.drop_table('attendance_evidences')
    op.drop_table('employee_bank_details')
    op.drop_table('workweek_policies')
    op.drop_index(op.f('ix_attendance_sessions_employee_id'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_work_date_local'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_session_emp_date'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_session_emp_open'), table_name='attendance_sessions')
    op.drop_table('attendance_sessions')
    op.drop_index(op.f('ix_leave_balance_emp_year_month'), table_name='leave_balances')
    op.drop_index(op.f('ix_leave_balances_employee_id'), table_name='leave_balances')
    op.drop_table('leave_balances')
    op.drop_index(op.f('ix_leave_requests_employee_id'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_end_datetime'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_start_datetime'), table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_index(op.f('ix_holiday_calendar_holiday_date'), table_name='holiday_calendar')
    op.drop_index(op.f('ix_holiday_calendar_region'), table_name='holiday_calendar')
    op.drop_index(op.f('ix_holiday_region_date'), table_name='holiday_calendar')
    op.drop_table('holiday_calendar')
    op.drop_index(op.f('ix_employee_profiles_employee_id'), table_name='employee_profiles')
    op.drop_table('employee_profiles')
    op.drop_table('employee_salaries')
    op.drop_index(op.f('ix_attendance_day_emp_month'), table_name='attendance_days')
    op.drop_index(op.f('ix_attendance_days_employee_id'), table_name='attendance_days')
    op.drop_table('attendance_days')
    op.drop_index(op.f('ix_employees_aadhar_number'), table_name='employees')
    op.drop_index(op.f('ix_employees_department'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_pan_number'), table_name='employees')
    op.drop_index(op.f('ix_employees_region'), table_name='employees')
    op.drop_table('employees')
    op.drop_table('worklogs')
    op.drop_index(op.f('ix_employee_shift_assignments_effective_from'), table_name='employee_shift_assignments')
    op.drop_index(op.f('ix_employee_shift_assignments_employee_id'), table_name='employee_shift_assignments')
    op.drop_index(op.f('ix_shift_assign_emp_from'), table_name='employee_shift_assignments')
    op.drop_table('employee_shift_assignments')
    op.drop_table('admins')
    op.drop_index(op.f('ix_payroll_policy_rules_id'), table_name='payroll_policy_rules')
    op.drop_table('payroll_policy_rules')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_table('salary_breakdowns')
    op.drop_index(op.f('ix_grace_policy_shift'), table_name='shift_grace_policies')
    op.drop_table('shift_grace_policies')
    op.drop_index(op.f('ix_leave_types_code'), table_name='leave_types')
    op.drop_table('leave_types')
    op.drop_index(op.f('ix_shifts_name'), table_name='shifts')
    op.drop_table('shifts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shifts',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('shifts_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('total_hours', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_night', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.CheckConstraint('total_hours >= 1 AND total_hours <= 24', name='ck_shift_total_hours'),
    sa.PrimaryKeyConstraint('id', name='shifts_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_shifts_name'), 'shifts', ['name'], unique=True)
    op.create_table('leave_types',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('leave_types_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('unit', postgresql.ENUM('DAY', 'HOUR', name='leave_unit_enum'), autoincrement=False, nullable=False),
    sa.Column('is_paid', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('allow_half_day', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('allow_permission_hours', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('duration_days', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('monthly_limit', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('yearly_limit', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('carry_forward_allowed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.CheckConstraint("code::text ~ '^[A-Z]{2,16}$'::text", name='ck_leave_type_code'),
    sa.PrimaryKeyConstraint('id', name='leave_types_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_leave_types_code'), 'leave_types', ['code'], unique=True)
    op.create_table('shift_grace_policies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shift_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('grace_type', postgresql.ENUM('BEFORE_START', 'AFTER_END', 'BOTH', name='grace_type_enum'), autoincrement=False, nullable=False),
    sa.Column('applies_to', postgresql.ENUM('LATE_ARRIVAL', 'EARLY_EXIT', 'UNDERWORK', name='applies_to_enum'), autoincrement=False, nullable=False),
    sa.Column('excused_minutes', sa.INTEGER(), server_default=sa.text('30'), autoincrement=False, nullable=False),
    sa.Column('effective_from', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('effective_to', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.CheckConstraint('excused_minutes >= 0 AND excused_minutes <= 120', name=op.f('ck_grace_minutes')),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name=op.f('shift_grace_policies_shift_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('shift_grace_policies_pkey')),
    sa.UniqueConstraint('shift_id', 'applies_to', 'effective_from', name=op.f('uq_grace_policy'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_grace_policy_shift'), 'shift_grace_policies', ['shift_id', 'effective_from'], unique=False)
    op.create_table('salary_breakdowns',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_salary_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rule_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('rule_type', postgresql.ENUM('ALLOWANCE', 'DEDUCTION', name='rule_type_enum'), autoincrement=False, nullable=False),
    sa.Column('applies_to', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_salary_id'], ['employee_salaries.id'], name=op.f('salary_breakdowns_employee_salary_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('salary_breakdowns_pkey'))
    )
    op.create_table('expenses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('category', postgresql.ENUM('FOOD', 'TRANSPORT', 'UTILITIES', 'ENTERTAINMENT', 'SOFTWARE', 'HEALTH', 'SHOPPING', 'OTHER', name='expense_category'), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('added_by', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('expenses_pkey'))
    )
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.create_table('payroll_policy_rules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('payroll_policy_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rule_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('is_percentage', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('applies_to', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('rule_type', postgresql.ENUM('ALLOWANCE', 'DEDUCTION', name='rule_type_enum'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['payroll_policy_id'], ['payroll_policies.id'], name=op.f('payroll_policy_rules_payroll_policy_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('payroll_policy_rules_pkey'))
    )
    op.create_index(op.f('ix_payroll_policy_rules_id'), 'payroll_policy_rules', ['id'], unique=False)
    op.create_table('admins',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('is_super_admin', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('admins_pkey')),
    sa.UniqueConstraint('admin_id', name=op.f('admins_admin_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('employee_shift_assignments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('shift_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('effective_from', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('effective_to', sa.DATE(), autoincrement=False, nullable=True),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name=op.f('ck_shift_assign_range')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name=op.f('employee_shift_assignments_employee_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name=op.f('employee_shift_assignments_shift_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('employee_shift_assignments_pkey')),
    sa.UniqueConstraint('employee_id', 'shift_id', 'effective_from', name=op.f('uq_shift_assign_start'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_shift_assign_emp_from'), 'employee_shift_assignments', ['employee_id', 'effective_from'], unique=False)
    op.create_index(op.f('ix_employee_shift_assignments_employee_id'), 'employee_shift_assignments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_shift_assignments_effective_from'), 'employee_shift_assignments', ['effective_from'], unique=False)
    op.create_table('worklogs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('work_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('task', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('duration_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('work_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('worklogs_pkey'))
    )
    op.create_table('employees',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('employees_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('father_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('date_of_joining', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('date_of_leaving', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('mobile_number', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('marital_status', postgresql.ENUM('SINGLE', 'MARRIED', name='maritalstatus'), autoincrement=False, nullable=False),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('permanent_address', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('designation', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('department', postgresql.ENUM('HR', 'IT', 'SALES', 'FINANCE', 'MARKETING', name='department'), autoincrement=False, nullable=False),
    sa.Column('profile_picture', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('pan_number', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('aadhar_number', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('bank_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ifsc_code', sa.VARCHAR(length=11), autoincrement=False, nullable=True),
    sa.Column('region', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='employees_pkey'),
    sa.UniqueConstraint('aadhar_number', name='uq_employee_aadhar_number', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('email', name='uq_employee_email', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('employee_id', name='uq_employee_employee_id', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('mobile_number', name='uq_employee_mobile_number', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('pan_number', name='uq_employee_pan_number', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_employees_region'), 'employees', ['region'], unique=False)
    op.create_index(op.f('ix_employees_pan_number'), 'employees', ['pan_number'], unique=True)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_index(op.f('ix_employees_employee_id'), 'employees', ['employee_id'], unique=True)
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_index(op.f('ix_employees_department'), 'employees', ['department'], unique=False)
    op.create_index(op.f('ix_employees_aadhar_number'), 'employees', ['aadhar_number'], unique=True)
    op.create_table('attendance_days',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('work_date_local', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('seconds_worked', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('first_check_in_utc', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_check_out_utc', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('Present', 'Absent', 'Leave', 'Holiday', 'Weekend', name='day_status_enum'), autoincrement=False, nullable=False),
    sa.Column('expected_seconds', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('paid_leave_seconds', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('overtime_seconds', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('underwork_seconds', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unpaid_seconds', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('leave_type_code', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('lock_flag', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('seconds_worked >= 0', name=op.f('ck_day_nonnegative')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name=op.f('attendance_days_employee_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('attendance_days_pkey')),
    sa.UniqueConstraint('employee_id', 'work_date_local', name=op.f('uq_attendance_day_emp_date'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_attendance_days_employee_id'), 'attendance_days', ['employee_id'], unique=False)
    op.create_index(op.f('ix_attendance_day_emp_month'), 'attendance_days', ['employee_id', 'work_date_local'], unique=False)
    op.create_table('employee_salaries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('base_salary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('gross_salary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('payroll_policy_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['payroll_policy_id'], ['payroll_policies.id'], name=op.f('employee_salaries_payroll_policy_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('employee_salaries_pkey'))
    )
    op.create_table('employee_profiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('employee_code', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('profile_bucket', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('profile_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('profile_mime', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('profile_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('profile_updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name=op.f('employee_profiles_employee_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('employee_profiles_pkey')),
    sa.UniqueConstraint('employee_id', name=op.f('employee_profiles_employee_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_employee_profiles_employee_id'), 'employee_profiles', ['employee_id'], unique=True)
    op.create_table('holiday_calendar',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('holiday_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('is_paid', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('region', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('recurs_annually', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('holiday_calendar_pkey'))
    )
    op.create_index(op.f('ix_holiday_region_date'), 'holiday_calendar', ['region', 'holiday_date'], unique=False)
    op.create_index(op.f('ix_holiday_calendar_region'), 'holiday_calendar', ['region'], unique=False)
    op.create_index(op.f('ix_holiday_calendar_holiday_date'), 'holiday_calendar', ['holiday_date'], unique=False)
    op.create_table('leave_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('leave_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('requested_unit', postgresql.ENUM('DAY', 'HALF_DAY', 'HOUR', name='leave_req_unit_enum'), autoincrement=False, nullable=False),
    sa.Column('requested_hours', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='leave_status_enum'), autoincrement=False, nullable=False),
    sa.Column('approver_employee_id', sa.VARCHAR(length=9), autoincrement=False, nullable=True),
    sa.Column('decided_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('reason', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('end_datetime >= start_datetime', name=op.f('ck_leave_req_range')),
    sa.ForeignKeyConstraint(['approver_employee_id'], ['employees.employee_id'], name=op.f('leave_requests_approver_employee_id_fkey')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name=op.f('leave_requests_employee_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], name=op.f('leave_requests_leave_type_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('leave_requests_pkey'))
    )
    op.create_index(op.f('ix_leave_requests_start_datetime'), 'leave_requests', ['start_datetime'], unique=False)
    op.create_index(op.f('ix_leave_requests_end_datetime'), 'leave_requests', ['end_datetime'], unique=False)
    op.create_index(op.f('ix_leave_requests_employee_id'), 'leave_requests', ['employee_id'], unique=False)
    op.create_table('leave_balances',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('leave_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('opening', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=False),
    sa.Column('accrued', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=False),
    sa.Column('used', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=False),
    sa.Column('adjusted', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=False),
    sa.Column('closing', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=False),
    sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.CheckConstraint('year >= 1970 AND year <= 2100', name=op.f('ck_leave_balance_year')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name=op.f('leave_balances_employee_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], name=op.f('leave_balances_leave_type_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('leave_balances_pkey')),
    sa.UniqueConstraint('employee_id', 'leave_type_id', 'year', 'month', name=op.f('uq_leave_balance_emp_type_year_month'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_leave_balances_employee_id'), 'leave_balances', ['employee_id'], unique=False)
    op.create_index(op.f('ix_leave_balance_emp_year_month'), 'leave_balances', ['employee_id', 'year', 'month'], unique=False)
    op.create_table('attendance_sessions',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('attendance_sessions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('check_in_utc', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('check_out_utc', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('work_date_local', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('check_out_utc IS NULL OR check_out_utc >= check_in_utc', name='ck_session_chronology'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name='attendance_sessions_employee_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='attendance_sessions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_session_emp_open'), 'attendance_sessions', ['employee_id', 'check_out_utc'], unique=False)
    op.create_index(op.f('ix_session_emp_date'), 'attendance_sessions', ['employee_id', 'work_date_local'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_work_date_local'), 'attendance_sessions', ['work_date_local'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_employee_id'), 'attendance_sessions', ['employee_id'], unique=False)
    op.create_table('workweek_policies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('region', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('policy_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('workweek_policies_pkey'))
    )
    op.create_table('employee_bank_details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bank_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('account_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('ifsc_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('branch_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('employee_bank_details_employee_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('employee_bank_details_pkey'))
    )
    op.create_table('attendance_evidences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('evidence_type', postgresql.ENUM('check_in', 'check_out', name='evidence_type_enum'), autoincrement=False, nullable=False),
    sa.Column('image_bucket', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('image_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('image_mime', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('image_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('verification_notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.id'], name=op.f('attendance_evidences_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('attendance_evidences_pkey'))
    )
    op.create_index(op.f('ix_evidence_verified'), 'attendance_evidences', ['verified'], unique=False)
    op.create_index(op.f('ix_evidence_session_type'), 'attendance_evidences', ['session_id', 'evidence_type'], unique=False)
    op.create_table('payroll_policies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('effective_from', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('effective_to', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('payroll_policies_pkey'))
    )
    op.create_index(op.f('ix_payroll_policies_id'), 'payroll_policies', ['id'], unique=False)
    op.create_table('checkin_monitoring',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('monitored_at_utc', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('cpu_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('memory_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('active_apps', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('visited_sites', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.id'], name=op.f('checkin_monitoring_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('checkin_monitoring_pkey'))
    )
    op.create_index(op.f('ix_checkin_monitoring_session_id'), 'checkin_monitoring', ['session_id'], unique=False)
    op.create_table('monthly_employee_summaries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('month_start', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('total_work_days', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('present_days', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('holiday_days', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('weekend_days', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('leave_days', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('paid_leave_hours', sa.NUMERIC(precision=8, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('unpaid_leave_hours', sa.NUMERIC(precision=8, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('pending_leave_hours', sa.NUMERIC(precision=8, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('total_worked_hours', sa.NUMERIC(precision=10, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('expected_hours', sa.NUMERIC(precision=10, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('overtime_hours', sa.NUMERIC(precision=10, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('underwork_hours', sa.NUMERIC(precision=10, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('leave_type_breakdown', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('paid_leave_days', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('unpaid_leave_days', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('pending_leave_days', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('monthly_employee_summaries_pkey')),
    sa.UniqueConstraint('employee_id', 'month_start', name=op.f('uq_monthly_summary_emp_month'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_monthly_summary_emp_month'), 'monthly_employee_summaries', ['employee_id', 'month_start'], unique=False)
    # ### end Alembic commands ###
