"""Add foreign key to expenses

Revision ID: 7c1e00e5b68e
Revises: 511b9f7ebdd0
Create Date: 2025-09-29 12:42:45.203710

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "7c1e00e5b68e"
down_revision: Union[str, Sequence[str], None] = "511b9f7ebdd0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
