"""Add expenses and other tables

Revision ID: bedc2728821a
Revises: 4a37601873f6
Create Date: 2025-09-29 12:52:24.196166

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "bedc2728821a"
down_revision: Union[str, Sequence[str], None] = "4a37601873f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
