"""Add Admin table

Revision ID: c778e18d2711
Revises: bedc2728821a
Create Date: 2025-09-29 13:56:36.868593

"""

from typing import Sequence, Union

from alembic import op  # type: ignore[attr-defined]
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c778e18d2711"
down_revision: Union[str, Sequence[str], None] = "bedc2728821a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admins",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("admin_id", sa.String(length=80), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_super_admin", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_admins_admin_id"), "admins", ["admin_id"], unique=True)
    op.create_index(op.f("ix_admins_id"), "admins", ["id"], unique=False)
    op.create_table(
        "expenses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("added_by", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_expenses_id"), "expenses", ["id"], unique=False)
    op.create_table(
        "attendance_days",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("employee_id", sa.String(length=50), nullable=False),
        sa.Column("work_date_local", sa.Date(), nullable=False),
        sa.Column("seconds_worked", sa.Integer(), nullable=False),
        sa.Column("first_check_in_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_check_out_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.CheckConstraint("seconds_worked >= 0", name="ck_day_nonnegative"),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.employee_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("employee_id", "work_date_local", name="uq_attendance_day"),
    )
    op.create_index(
        "ix_attendance_day_emp_month",
        "attendance_days",
        ["employee_id", "work_date_local"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attendance_days_employee_id"), "attendance_days", ["employee_id"], unique=False
    )
    op.create_table(
        "attendance_sessions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("employee_id", sa.String(length=50), nullable=False),
        sa.Column("check_in_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("check_out_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("work_date_local", sa.Date(), nullable=False),
        sa.CheckConstraint(
            "(check_out_utc IS NULL) OR (check_out_utc >= check_in_utc)",
            name="ck_session_chronology",
        ),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.employee_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_attendance_sessions_employee_id"),
        "attendance_sessions",
        ["employee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attendance_sessions_work_date_local"),
        "attendance_sessions",
        ["work_date_local"],
        unique=False,
    )
    op.create_index(
        "ix_session_emp_open", "attendance_sessions", ["employee_id", "check_out_utc"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_session_emp_open", table_name="attendance_sessions")
    op.drop_index(op.f("ix_attendance_sessions_work_date_local"), table_name="attendance_sessions")
    op.drop_index(op.f("ix_attendance_sessions_employee_id"), table_name="attendance_sessions")
    op.drop_table("attendance_sessions")
    op.drop_index(op.f("ix_attendance_days_employee_id"), table_name="attendance_days")
    op.drop_index("ix_attendance_day_emp_month", table_name="attendance_days")
    op.drop_table("attendance_days")
    op.drop_index(op.f("ix_expenses_id"), table_name="expenses")
    op.drop_table("expenses")
    op.drop_index(op.f("ix_admins_id"), table_name="admins")
    op.drop_index(op.f("ix_admins_admin_id"), table_name="admins")
    op.drop_table("admins")
    # ### end Alembic commands ###
