"""Create employees table and maritalstatus enum

Revision ID: d71fb191dc92
Revises: 
Create Date: 2025-09-29 12:35:48.681465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd71fb191dc92'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('father_name', sa.String(length=30), nullable=False),
    sa.Column('employee_id', sa.String(length=9), nullable=False),
    sa.Column('date_of_joining', sa.Date(), nullable=False),
    sa.Column('date_of_leaving', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('mobile_number', sa.String(length=10), nullable=False),
    sa.Column('marital_status', sa.Enum('SINGLE', 'MARRIED', name='maritalstatus'), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('permanent_address', sa.Text(), nullable=False),
    sa.Column('designation', sa.String(length=30), nullable=False),
    sa.Column('department', sa.Enum('HR', 'IT', 'SALES', 'FINANCE', 'MARKETING', name='department'), nullable=False),
    sa.Column('profile_picture', sa.Text(), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_employee_email'),
    sa.UniqueConstraint('employee_id', name='uq_employee_employee_id'),
    sa.UniqueConstraint('mobile_number', name='uq_employee_mobile_number')
    )
    op.create_index(op.f('ix_employees_department'), 'employees', ['department'], unique=False)
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_index(op.f('ix_employees_employee_id'), 'employees', ['employee_id'], unique=True)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_index(op.f('ix_employees_department'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
